- src/Arcane.Framework.csproj
- src/Providers/StreamContext/StreamContextProvider.cs
- src/Services/Base/IStreamContext.cs
- src/Services/Base/IStreamContextWriter.cs
- src/Services/Base/IStreamOptions.cs
- src/Services/StreamRunnerService.cs
- test/Fixtures/ServiceFixture.cs
Implemented:
- Added the `IStreamContext` interface for stream implementations.
- Added the `AddStreamContext` extension method fir `IServiceCollection`
> Add stream context providers

- src/Providers/StreamContext/StreamContextProvider.cs
Part of #18
Implemented:
- Make the JSON serializer default to deserializing properties in a case-insensitive manner.
> Make property names case-insensitive by default

- src/Services/StreamRunnerService.cs
Part of #18
Implemented:
- Remove the streamContext from StreamRunnerService since we enrich log messages with stream id.
> Simplify StreamRunnerService

- src/Sources/RestApi/Models/PageResolverConfiguration.cs
- src/Sources/RestApi/Services/PageResolvers/PageOffsetResolver.cs
- src/Sources/RestApi/Services/UriProviders/PagedUriProvider.cs
Implemented:
- Add ability to set first page offset
> Add start offset

- src/Sources/RestApi/Services/PageResolvers/PageOffsetResolver.cs
Fixes #36
Set page number to statOffset to startOffset instead of 0
> Set start page to startOffset instead of 0

- src/Sources/RestApi/Services/PageResolvers/PageOffsetResolver.cs
Implemented:
- Fix incorrect backfill behavior
> Fix source backfill

- src/Contracts/Annotations.cs
- src/Providers/Hosting/HostBuilderExtensions.cs
- src/Providers/Hosting/StreamHostBuilderContext.cs
- src/Providers/StreamContext.cs
- test/Providers/Hosting/HostBuilderExtensionsTests.cs
- test/Providers/TestCases/TestGraphBuilder.cs
- test/Providers/TestCases/TestStreamContext.cs
Part of https://github.com/SneaksAndData/arcane-framework/issues/5
Implemented:
- Implemented unit tests that validate DI container setup.
- Implemented unit tests that validate proper exception handling in the `RunStream` method.
- Fixed bugs found during testing.
> Add unit tests for Hosting Extensions

- README.md
Part of https://github.com/SneaksAndData/arcane-docs/issues/1
Implemented:
- Added the repository structure description to README.md
**NOTE:** Hyperlinks will be added a later stage when the documentation website is ready.
> Add the repository structure in README.md

- src/Sources/RestApi/RestApiSource.cs
- src/Sources/RestApi/Services/AuthenticatedMessageProviders/DynamicBearerAuthenticatedMessageProvider.cs
- src/Sources/RestApi/Services/PageResolvers/PageNextTokenResolver.cs
- src/Sources/RestApi/Services/RestApiTemplate.cs
- src/Sources/RestApi/Services/UriProviders/SimpleUriProvider.cs
- test/Sources/PageResolverTests.cs
This is cherry-pick changes form https://github.com/SneaksAndData/arcane/pull/350
> Enhance dynamic auth capabilities

- src/Sources/RestApi/Services/AuthenticatedMessageProviders/DynamicBearerAuthenticatedMessageProvider.cs
This pull request is a cherry-pick from private repo
> Cherry-pick forgotten changes from private repo

- src/Sources/BlobStorage/BlobStorageSource.cs
- test/Sources/BlobStorageSourceTests.cs
Use absolute path in BS source.
> Fix incorrect path variable

- src/Arcane.Framework.csproj
Part of https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/issues/7
Implemented:
- Pack SQL Snippets to the nuget package
> Pack SQL snippets to the nuget package

- src/Arcane.Framework.csproj
Fixes #92
Implemented:
- Publish the content proper way
> Add content item group

- src/Sources/SqlServer/SqlServerSource.cs
- test/Sources/SqlServerSourceTests.cs
Part of #108
Implemented:
- Added ability to configure `changeCaptureInterval` for `SqlSource` in Arcane.Framework
> Fix change capture interval behavior

- src/Sources/SqlServer/SqlServerSource.cs
- test/Sources/SqlServerSourceTests.cs
Fixes #109
Implemented:
- When the current reader is complete, the SQL Source should reschedule to read the next rows, rather than completing.
> Reschedule changes in SQL Server Source

- src/Sources/SqlServer/SqlServerChangeTrackingSource.cs
Fixes #117
Implemented:
- Explicit SQL transaction operations, added in past are removed since it seems that this transaction makes no sense and can cause timeouts in SQL server streaming plugin.
> Remove explicit transaction from SqlServerChangeTrackingSource

- src/Sources/CdmChangeFeedSource/CdmChangeFeedSource.cs
- test/Sources/CdmChangeFeedSourceTests.cs
Resolves #119
Implemented:
- The lookBack parameter for CdmFeedSource
> Implement look back interval for CDM change feed source

- src/Sources/CdmChangeFeedSource/CdmChangeFeedSource.cs
Fixes #120
Implemented:
- Add some logging
> Add logging for last processing timestamp

- src/Sources/SqlServer/SqlServerChangeTrackingSource.cs
Part of #117
Implemented:
- Add the command timeout in GetChangeTrackingVersion method
> Add the command timeout in GetChangeTrackingVersion method

- src/Sources/SqlServer/SqlServerChangeTrackingSource.cs
Part of #117
Implemented:
- Call `Dispose()` method on SQL command to avoid resource leaks.
Try approach from the following comment: https://github.com/dotnet/SqlClient/issues/647#issuecomment-719491954
> Dispose SQL commands in the SQL source

- src/Sinks/Json/MultilineJsonSink.cs
- src/Sinks/Parquet/ParquetSink.cs
- test/SinkTests/MultilineJsonSinkTest.cs
- test/SinkTests/ParquetSinkTests.cs
Fixes #110
Implemented:
- Add proper error handling in Arcane Sink.
> Handle error in Sinks properly
